# my-snowflake-db:
#   target: dev
#   outputs:
#     dev:
#       type: snowflake
#       account: eacytbe-jw16682
#       # User/password auth
#       user: mehtab1997
#       password: Germany@1234

#       #role: SYSADMIN
#       database: RAW
#       warehouse: DWH
#       schema: ENERGY
#       threads: 1
#       client_session_keep_alive: False
#       #query_tag: [anything]

#       # optional
#       connect_retries: 0 # default 0
#       connect_timeout: 10 # default: 10
#       retry_on_database_errors: False # default: false
#       retry_all: False  # default: false
#       reuse_connections: False # default: false (available v1.4+)


my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: eacytbe-jw16682

      # User/password auth
      user: mehtab1997
      password: Germany@1234

      role: ACCOUNTADMIN
      database: RAW
      warehouse: DWH
      schema: ENERGY
      threads: 1
      client_session_keep_alive: False
      #query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)