
my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: eacytbe-jw16682

      # User/password auth
      user: mehtab1997
      password: Germany@1234

      role: ACCOUNTADMIN
      database: RAW
      warehouse: COMPUTE_WH #DWH
      schema: ENERGY
      threads: 4
      client_session_keep_alive: False
      #query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 20 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
      partial_parse: Flalse