version: 2

seeds:
  - name: products
    description: store product details per row
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: deleted
        description: 0 means it is not deleted 1 means its deleted
        tests:
          - accepted_values:
              values: [1,0]
      - name: modificationdate
        tests:
          - not_null
      - name: productcode
        tests:
          - not_null
          - unique
      - name: productname
        tests:
          - not_null

  - name: prices
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: productid
        tests:
          - relationships:
              to: ref('products')
              field: id